### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by ghost** [mefyl/dune-cache-daemon#2]
As mentioned, we need to change the name of the project. At this point, sietch feels more like a system in the dune world rather than a system on its own, and it will be simpler to remember what it is if we use a descriptive name with `dune` in it.

Unless there is an obvious better choice, let's go for `dune-shared-cache-daemon`.

**Comment by mefyl** [comment]
That's hella long =) . `dune-cache-daemon` ? It's the only one, it's not like there is a non-shared cache daemon.

Anyway I'll go with the common decision.

**Comment by ghost** [comment]
`dune-cache-daemon` is fine :+1:
